# Generated by Django 3.2.7 on 2021-09-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('NIT', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=10)),
                ('Direccion', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('Cargo', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('Celular', models.CharField(max_length=10)),
                ('Direccion', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=50)),
                ('Estado', models.BooleanField(default=True)),
                ('Compañia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contactos.empresa')),
            ],
        ),
    ]
