# Generated by Django 3.2.7 on 2021-09-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='NIT',
            field=models.CharField(max_length=11),
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='Id',
        ),
        migrations.AddField(
            model_name='contacto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
